FROM eclipse-temurin:25-jre
ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en'
WORKDIR /work/
COPY target/quarkus-app/lib/ /work/lib/
COPY target/quarkus-app/*.jar /work/
COPY target/quarkus-app/app/ /work/app/
COPY target/quarkus-app/quarkus/ /work/quarkus/
EXPOSE 8080
ENTRYPOINT ["java","-jar","/work/quarkus-run.jar"]

